/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AppRewardsRouteImport } from './routes/app/rewards'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppCreateBudgetRouteImport } from './routes/app/create-budget'
import { Route as ApiAnalyzeTransactionsRouteImport } from './routes/api/analyze-transactions'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/app/rewards',
  path: '/app/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateBudgetRoute = AppCreateBudgetRouteImport.update({
  id: '/app/create-budget',
  path: '/app/create-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeTransactionsRoute = ApiAnalyzeTransactionsRouteImport.update({
  id: '/api/analyze-transactions',
  path: '/api/analyze-transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/analyze-transactions': typeof ApiAnalyzeTransactionsRoute
  '/app/create-budget': typeof AppCreateBudgetRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/analyze-transactions': typeof ApiAnalyzeTransactionsRoute
  '/app/create-budget': typeof AppCreateBudgetRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/analyze-transactions': typeof ApiAnalyzeTransactionsRoute
  '/app/create-budget': typeof AppCreateBudgetRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/analyze-transactions'
    | '/app/create-budget'
    | '/app/history'
    | '/app/profile'
    | '/app/rewards'
    | '/auth/confirm'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/analyze-transactions'
    | '/app/create-budget'
    | '/app/history'
    | '/app/profile'
    | '/app/rewards'
    | '/auth/confirm'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/analyze-transactions'
    | '/app/create-budget'
    | '/app/history'
    | '/app/profile'
    | '/app/rewards'
    | '/auth/confirm'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAnalyzeTransactionsRoute: typeof ApiAnalyzeTransactionsRoute
  AppCreateBudgetRoute: typeof AppCreateBudgetRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rewards': {
      id: '/app/rewards'
      path: '/app/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create-budget': {
      id: '/app/create-budget'
      path: '/app/create-budget'
      fullPath: '/app/create-budget'
      preLoaderRoute: typeof AppCreateBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-transactions': {
      id: '/api/analyze-transactions'
      path: '/api/analyze-transactions'
      fullPath: '/api/analyze-transactions'
      preLoaderRoute: typeof ApiAnalyzeTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAnalyzeTransactionsRoute: ApiAnalyzeTransactionsRoute,
  AppCreateBudgetRoute: AppCreateBudgetRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
